// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BreezeButton: typeof import('./components/breeze/Button.vue')['default']
    BreezeCheckbox: typeof import('./components/breeze/Checkbox.vue')['default']
    BreezeDropdown: typeof import('./components/breeze/Dropdown.vue')['default']
    BreezeDropdownLink: typeof import('./components/breeze/DropdownLink.vue')['default']
    BreezeInput: typeof import('./components/breeze/Input.vue')['default']
    BreezeInputError: typeof import('./components/breeze/InputError.vue')['default']
    BreezeLabel: typeof import('./components/breeze/Label.vue')['default']
    BreezeNavLink: typeof import('./components/breeze/NavLink.vue')['default']
    BreezeResponsiveNavLink: typeof import('./components/breeze/ResponsiveNavLink.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    Default: typeof import('./components/Default.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IFa6SolidBars: typeof import('~icons/fa6-solid/bars')['default']
    IFa6SolidGaugeHigh: typeof import('~icons/fa6-solid/gauge-high')['default']
    IFa6SolidUmbrella: typeof import('~icons/fa6-solid/umbrella')['default']
    IMaterialSymbolsLockPerson: typeof import('~icons/material-symbols/lock-person')['default']
    IMaterialSymbolsPerson: typeof import('~icons/material-symbols/person')['default']
    IMaterialSymbolsSignalCellularAlt: typeof import('~icons/material-symbols/signal-cellular-alt')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    MultiSelectInput: typeof import('./components/MultiSelectInput.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    SelectInput: typeof import('./components/SelectInput.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    ToastList: typeof import('./components/ToastList.vue')['default']
    ToastListItem: typeof import('./components/ToastListItem.vue')['default']
  }
}
